### ISSUE TITLE
RTCPeerConnection.getStats: What to do with 'selector' argument?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#116] opened 2016-12-19 16:19 UTC
The description at https://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-getStats-Promise-RTCStatsReport--MediaStreamTrack-selector is poorly defined.

"Start gathering the stats indicated by selectorArg. If selectorArg is null, stats must be gathered for the whole RTCPeerConnection object."

This could mean just a single RTCMediaStreamTrackStats object or could mean it and any dictionary referencing it. If the idea is to 1) make it more lightweight and 2) limit the result so that it is easier to go through, questions arise: Does this API achieve this? Has it been implemented?

Chrome's new getStats soon to be shipped does not make use of the selector argument, and it seems difficult to achieve 1) and 2).

Do we remove this or clarify its description? What if you're interested in other things that are not related to tracks? Would a different type of selector argument make more sense, such as dictionary IDs or types, should we replace it?

(Maybe this issue belongs to https://github.com/w3c/webrtc-pc/issues?)

**Comment by vr000m** [comment] 2016-12-19 16:25
Currently the selector typically are basically fetching data from specific `tracks`. The examples typically are as follows:

```js 
// get audio track RTTs.
var selector = pc.getRemoteStreams()[0].getAudioTracks()[0];
var rttMeasures = [];
setTimeout(function () {
  pc.getStats(selector, function (report) {
    for (var i in report) {
      var now = report[i];
      if (now.type == "outbound-rtp") {
        rttMeasures.append(now.roundTripTime);
       }
    }
  }, logError);
}, 1000);
```

**Comment by jan-ivar** [comment] 2016-12-19 19:16
@vr000m Please use spec in examples. `getRemoteStreams` is gone, stats are [maplike](https://jsfiddle.net/jib1/4ea0nj0s/), and callbacks deprecated. if we don't get it right, no-one will. Here's the spec:
```js
var wait = ms => new Promise(resolve => setTimeout(resolve, ms));

// get audio track RTTs.
var selector = pc.getReceivers()[0].track.getAudioTracks()[0];
var rttMeasures = [];
wait(1000).then(() => pc.getStats(selector))
.then(report => report.forEach(now => {
  if (now.type == "outbound-rtp") {
    rttMeasures.append(now.roundTripTime);
  }
}))
.catch(logError);
```

On the upside, since no-one gets this right, few should be broken by missing hyphens (Firefox [plans]() to give hyphen to me above, but not @vr000m (because he used non-maplike).

**Comment by fippo** [comment] 2016-12-19 21:05
I typed some notes earlier while on the plane:
what is the idea behind the selector argument to getStats()?

The optional selector argument to getStats() is a MediaStreamTrack.
It might imply that the caller is only interested in information about that track. For audiotracks, the caller might look for information about audio levels at a very high rate.
Calling getStats and then iterating the resulting map to find the report with the track id might be considered too heavy in such cases. Also it would signal the intent "I only care about this track" to the browser which would allow it to gather/update less information.

So lets assume we had an implementation of this selector that would only return the matching RTCMediaStreamTrackStats.
What would the ssrcIds be set to? (assuming #85 is fixed)
Would they point to an RTCRTPStreamStats object?
If so, I assume that this object has a transportId which points to an RTCTransportStats.
Which points to a selected candidate pair.

In the end, the call with the selector argument will have to return the complete set of statistics.
So what is the point? Is this simply an artifact of a previous statistics model that was not updated?

I can see this being marginally useful if the callback was something like this:
```
pc.getStats(track)
.then((reportForTrack, snowball) => {
  // look up *Id in snowball
})
```
which would save the initial iteration to find the right starting point.

**Comment by jan-ivar** [comment] 2016-12-19 22:06
@fippo Any way to limit the scope of what we need to gather is a plus IMHO. Yes, any record referenced by id would need to be included, but I don't see how this ends up being the complete set. An audio track should have no direct or indirect references to a video track (unless there are some back references I'm missing).

FWIW Firefox effectively filters out (skips) other tracks when a track is given as selector. You still get ICE stats. You can try it [here](https://jsfiddle.net/jib1/ncw14v8f/) (unless the diff is a fluke, it looks like we even filter out ICE candidates by track, who knew?)

That said, we haven't implemented all stats yet, so what to include in the presence of a selector in general is a good question (when should we include data channel stats for instance? Can data channels be selectors?)

**Comment by vr000m** [comment] 2016-12-19 23:51
@jan-ivar you are right, and thank you for providing the spec-client example. Just to reiterate, my earlier example was more towards highlighting how people use it today.

IMO, @callstats-io, we use it in a slightly different way. We query the getStats() the whole object at larger timescales, say 10-20s, to get the stats from (non-media tracks), e.g., candidate pairs. And more often from the audio and video tracks. Again, this was mostly to highlight the use-case.

**Comment by alvestrand** [comment] 2016-12-20 11:32
When we were ruminating about the selector in the office, we could think of some other useful definitions and selectors:
- Get the object with this stats ID (would allow the iteration in @jan-ivar 's sample to be done client-side) - probably would require gathering all objects UA-side, since we don't select this way currently
- Get all the objects with this stats type (trivially implementable UA-side)
- Make the selector mean "this track's stat object only" (and couple with individual-object lookup to get the stuff it refers to, if interesting)
- Make the selector mean "this track's stat object and every stat object that is referenced by an ID value in it (recursively)"

But it seemed scary to start down any of these without first discussing whether there was agreement on what the current text was intended to mean, and getting it either clarified or removed before continuing.


The last is probably the one closest to what the spec says today.

**Comment by fippo** [comment] 2016-12-20 11:52
I like the the first and third bullets and don't see much use for the fourth.

The second... if you find a way to make the signature distinguishable from the first (both would be DOMString?) then maybe.

**Comment by foolip** [comment] 2016-12-20 13:28
The important question from the point of view of shipping `getStats()` in Chromium is how likely it is that the current `optional MediaStreamTrack? selector` argument will remain.

It sounds like Gecko supports it and that it does *something*. @ShijunS, is `getStats()` implemented in Edge and does it support the selector argument?

**Comment by jan-ivar** [comment] 2016-12-20 18:55
FF has implemented the selector since [2013](https://bugzilla.mozilla.org/show_bug.cgi?id=902003); it's been in the spec even longer. I think it's here to stay.

The spec [says](http://w3c.github.io/webrtc-pc/#stats-selector): *"For a track to be a valid selector, it MUST be a MediaStreamTrack that is sent or received by the RTCPeerConnection object on which the stats request was issued. ... the browser emits (in the JavaScript) a set of statistics that it believes is relevant to the selector."*

Firefox does [exactly that](https://github.com/w3c/webrtc-stats/issues/116#issuecomment-268092437). Sure, flesh out the line of relevance, but no 180's please over details.

Benefit example: Users can get a specific track stats without looping over records:
```js
let rtp = [...(await pc.getStats(track)).values()].find(stat => stat.type == "outboundrtp");
let videoPackets = rtp.packetsSent;
```

**Comment by ShijunS** [comment] 2016-12-20 19:05
@foolip, Edge requires the selector in getStats() as well.

**Comment by alvestrand** [comment] 2016-12-20 21:41
@jan-ivar can you give a list of what Mozilla considers relevant to a track?

**Comment by alvestrand** [comment] 2016-12-20 21:51
@ShijunS can I ask you the same thing? It would be wonderful if we could converge this.

**Comment by jan-ivar** [comment] 2016-12-20 22:04
@alvestrand I already [gave an example](https://github.com/w3c/webrtc-stats/issues/116#issuecomment-268092437) in the form of code, for the subset we support (rtp, rtcp, ice).

If you're asking for a position, I'm sure smarter people can answer that, though I'd intuit:
* Any data that multiplies when a second track are added, is per-track, and filterable.
* Any included per-track data MUST include records it references by "foreign-key" `fooId` as well.
* Anything else, such as data channel should not be included when selecting on track.

**Comment by alvestrand** [comment] 2017-01-09 14:25
@jan-ivar can you make a jsfiddle with a complete example with selector?
Since you don't return the track object, it's a bit hard to see if we're succeeding or not.

**Comment by henbos** [comment] 2017-01-09 14:34
I tried with this https://jsfiddle.net/g9Lvkprh/ but got the same stats as without the selector, though I didn't get any track stats without a selector argument either.

**Comment by jan-ivar** [comment] 2017-01-09 17:11
@alvestrand I don't understand what you're asking me to provide. Fiddle wfm.

@henbos We don't implement *RTCMediaStreamTrackStats* (type `"track"`) yet. @alvestrand Is that what you mean with "track object"? To me, that stats object is just one of many that are track-related. For example, *RTCOutboundRTPStreamStats* (type `"outbound-rtp"`) is track-specific, in that you'll see separate objects of this type for each track (e.g. video vs. audio) you're sending.

Is anyone suggesting that a track selector only return the *RTCMediaStreamTrackStats* (type `"track"`) stats object? That would surprise me, and is not what we implement.

@henbos You're doing a single gUM track in your fiddle (`{audio: true, video: false}`) so it makes sense there's no difference. Firefox doesn't implement all stats yet. We don't implement datachannel stats for instance. All stats we implement so far happen to relate to some track.

If I change your fiddle to `{audio: true, video: true}`, then I see an `"outboundrtp"` object for the video (called `"outbound_rtp_video_1"`) when I get all stats, that I don't see when I provide the audio track as a selector. Makes sense?

Also, note you have a bug in your error handling: you proceed in spite of gUM error. Using the promise-api instead might help with that. Callback-based getStats has been removed from the spec, so we really should stop referring to it in public.

**Comment by henbos** [comment] 2017-01-09 17:38
@alvestrand Here is @jan-ivar's fiddle, linked to from his previous post: https://jsfiddle.net/jib1/ncw14v8f/

@jan-ivar OK that makes sense, I tried with audio+video now (after fixing my webcam) and it filters out `outboundrtp`s not related to the track like you describe.
I'm still confused as to why `getStats(track)` includes all `localcandidate`s, not just the selected pair. Or for that matter, why any pair/candidates are included when selecting by track.

I would have thought that `getStats(track)` would include `RTCMediaStreamTrackStats` for that track (stats.trackIdentifier == track.id) + any stats dictionaries _referencing or referenced by_ those track stats, and not candidates.

**Comment by nils-ohlmeier** [comment] 2017-01-09 22:38
@henbos the candidate and pair stats were added to Fx way before the spec even mentioned them. And they were added purely for purpose of our own tests to verify transport parameters of a running call.

Your point regarding localcandidates vs successful pair raises again the general question of the what the user is looking for. E.g. if getStats() gets called with the filter does he only want to see the successful pair, or is trying to find our if a relayed pair got generated but not used?

Providing the "right" transport stats for a track is actually not easy, because of bundle. E.g. if the track happens to be an m-line which is the bundle-slave, should we provide the pair of the bundle-master (which is a different m-line and track) or nothing at all?

I think the easiest solution forward regarding the filter is to not include any transport stats (ICE and DTLS/certs) at all if a filter was provided. And only provide the transport stats if getStats() gets called without a filter (and then provide everything: all candidates and pairs).

IMO the most sensible thing would be to move transport related stats over to the ICE and DTLS transport objects. And not deliver them with any track, but only for the unfiltered call.
Maybe a sensible alternative would be to add more/different filters to the getStats() call, to allow filtering down into the transport specifics stats only.
But I guess both of these would be pretty big changes at this point.

**Comment by henbos** [comment] 2017-01-10 09:43
"Maybe a sensible alternative would be to add more/different filters to the getStats() call, to allow filtering down into the transport specifics stats only." reminds me of what @alvestrand [just wrote](https://github.com/w3c/webrtc-stats/issues/130#issuecomment-271513425):
> History: We added selectors to the spec because we thought they'd be useful, and added tracks as a selector because that was the only clear case we could think of at that moment. The discussion tended to say "this will become an union, but since we only have one case now, we'll specify that case".

On the other hand, if you're looking for specific stats it's easy to filter them yourself. Using selectors for filtering makes more sense to me if they pick out only a small subset of the overall stats, just the thing(s) you're asking for (i.e. probably not a bunch of transport stats when asking for tracks), and hopefully at a lower cost than a full getStats() call.

**Comment by alvestrand** [comment] 2017-01-10 11:14
So we have both browsers being inconsistent with the suggestions for a sensible spec (Firefox returning transport information only, Chrome ignoring the selector argument).

**Comment by ShijunS** [comment] 2017-01-10 18:44
@Alvestrand, To add one more perspective, based on the selector (track), Edge returns stats with the following types: "inboundtrp", "outboundrtp", and "track". The results differ based on the specific track, e.g. whether it is audio/video or inbound/outbound.

**Comment by jan-ivar** [comment] 2017-01-10 19:35
@nils-ohlmeier Filtering in JS is so trivial, that for something to qualify as a selector, I think there also has to be a performance benefit (i.e. the implementation can skip a lot of gathering). Since there's (in theory!) no cap on the number of tracks that can be added to a peer connection, selecting on track makes sense based on that measure IMHO.

**Comment by henbos** [comment] 2017-01-11 09:23
@jan-ivar Thumbs up for "Filtering in JS is so trivial, that for something to qualify as a selector, I think there also has to be a performance benefit".

**Comment by henbos** [comment] 2017-01-11 09:25
@ShijunS Thanks! That type of filtering makes sense to me.

**Comment by alvestrand** [comment] 2017-01-11 10:18
This is actually a webrtc-pc change ..... I'll make a PR that says "do what Shijun says"; that makes sense to me, and is easily specifiable (I think, not having written it yet).

**Comment by jan-ivar** [comment] 2017-02-10 05:22
@alvestrand Here's a [map](https://docs.google.com/presentation/d/1sfVD5VAHg1K7Hee37kooAbGEajfNIhaKUWmbIRZoioI/) of the stats I image being returned for a selector (*receiver* in this case), based on an algorithm that includes everything referenced.

I have some question-marks in there, so if you could help me out that'd be great! PTAL.

**Comment by jan-ivar** [comment] 2017-02-10 22:30
E.g. selecting on a *receiver* would produce the follow stats objects:

* RTCInboundRTPStreamStats
  * RTCOutboundRTPStreamStats (associateStatsId)
  * RTCMediaStreamTrackStats (mediaTrackId)
  * RTCCodecStats (codecId)
  * RTCTransportStats (transportId)
    * RTCTransportStats (rtcpTransportStatsId)
    * RTCIceCandidatePairStats (selectedCandidatePairId)
      * RTCIceCandidateStats (localCandidateId)
      * RTCIceCandidateStats (remoteCandidateId)
    * RTCCertificateStats (localCertificateId)
    * RTCCertificateStats (remoteCertificateId)

and for a *sender* almost the same thing:

* RTCOutboundRTPStreamStats
  * RTCInboundRTPStreamStats (associateStatsId)
  * RTCMediaStreamTrackStats (mediaTrackId)
  * RTCCodecStats (codecId)
  * RTCTransportStats (transportId)
    * RTCTransportStats (rtcpTransportStatsId)
    * RTCIceCandidatePairStats (selectedCandidatePairId)
      * RTCIceCandidateStats (localCandidateId)
      * RTCIceCandidateStats (remoteCandidateId)
    * RTCCertificateStats (localCertificateId)
    * RTCCertificateStats (remoteCertificateId)

Does that look right?

**Comment by alvestrand** [comment] 2017-03-14 08:54
PR merged on webrtc-pc, so closing this one.

**Closed by alvestrand** 2017-03-14 08:54 UTC
Labels: PR exists
