### ISSUE TITLE
Exposing RTCIceCandidateStats.networkType might trigger fingerprinting

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-stats#374] opened 2018-09-28 21:06 UTC
Isn't it an issue to expose the fact that a host is vpn for instance?

**Comment by youennf** [comment] 2018-09-28 21:19
Or being able to know whether someone is connected over ethernet vs. wifi...
I am also wondering what an application might do of this particular information.

**Comment by vr000m** [comment] 2018-09-30 09:36
This is already exposed for http://wicg.github.io/netinfo/, we should make sure that the stats document references it.

We have found `networkType` to be very helpful for diagnostics. (during a call and also afterwards). At least in the case for diagnostics, knowing if the user was on a WiFi helps a lot. 

Not having done any study, I cannot say if the additional information helps with fingerprinting. Because, in several enterprises/homes, the ethernet and wifi work in the same address range. There are also situations when the networkType is wrong, because someone is tethering (for example: LTE over WiFi).

**Comment by youennf** [comment] 2018-09-30 10:27
> This is already exposed for http://wicg.github.io/netinfo/, we should make sure that the stats document references it.

http://wicg.github.io/netinfo/ acknowledges that this API causes fingerprinting issues.
And it refers to WebRTC to state that this is already leaking elsewhere.
There would be a circular reference if WebRTC stats would refer to this API.
And the netinfo API is not as widely implemented/endorsed as WebRTC.

User agents that want to prevent fingerprinting in WebRTC will probably also want to prevent fingerprinting in netinfo.

Note also that VPN is not an option in netinfo, and some efforts have been made to prevent VPN detection through WebRTC.

> We have found `networkType` to be very helpful for diagnostics. (during a call and also afterwards). At least in the case for diagnostics, knowing if the user was on a WiFi helps a lot.

For diagnostics, couldn't you infer this in most cases by looking at:
- Network metrics like packet loss
- IP addresses, including private IP addresses if getUserMedia is granted

In general, the more expensive a fingerprinting method, the less attractive and used it will be.
Network info API/WebRTC stats are making it cheap to get this information.

> Not having done any study, I cannot say if the additional information helps with fingerprinting. Because, in several enterprises/homes, the ethernet and wifi work in the same address range. There are also situations when the networkType is wrong, because someone is tethering (for example: LTE over WiFi).

If the info is wrong enough to prevent fingerprinting, it should probably not be exposed as it might prevent good diagnostics.

**Comment by vr000m** [comment] 2018-10-01 08:09
> For diagnostics, couldn't you infer this in most cases by looking at:
> 
> Network metrics like packet loss

Packet loss is a complicated metric because packet loss can appear due to congestion or due to the wireless channel. Knowing there was a wireless channel helps immensely.

> IP addresses, including private IP addresses if getUserMedia is granted

Knowing an IP address is not very useful in this regard. The IP address does not reveal networkType.

I maybe speaking about a minority of the apps, however. we and other companies, because of GDPR, COPTA, or HIPAA ---  drop/hash/encrypt the candidate pair IP addresses, and generally make it inaccessible except for specific use-cases listed in data privacy agreements (DPA). 

> > There are also situations when the networkType is wrong, because someone is tethering (for example: LTE over WiFi).
> >
> If the info is wrong enough to prevent fingerprinting, it should probably not be exposed as it might prevent good diagnostics

It still helps to know wireless was present.

**Comment by juberti** [comment] 2018-10-10 00:33
This information is incredibly valuable for debugging a production service. I am familiar with several bugs that have been found by slicing stats by network type.

However, one could imagine some of this data being more privileged, similar to the IP mode discussions.

**Comment by youennf** [comment] 2018-10-31 10:02
There was no consensus one way or the other on this particular issue.
There was consensus in acknowledging the potential issue in the spec.
I'll write a PR for the latter.

**Comment by youennf** [comment] 2018-10-31 10:05
Filed PR https://github.com/w3c/webrtc-stats/pull/380 for that purpose.
I do not think this PR is easily testable.

**Comment by youennf** [comment] 2018-11-30 18:03
Reading a bit more how webrtc-stats relate to webrtc-pc, it seems that if we want to precise how/when is exposed networkType, webrtc-pc might be a better place.
Should we move this issue there?

**Comment by henbos** [comment] 2019-08-29 13:46
Do we need to revisit this issue now, or is the warning added in #380 enough?
Is this something we are hiding with mDNS?

**Comment by juberti** [comment] 2019-08-29 17:22
In the drive-by (mode 2) case where mDNS is used, we don't bind to a specific interface so I don't think this information is filled in (IOW, no action needed right now.) @tqsw to confirm.

**Comment by youennf** [comment] 2019-08-30 12:43
> Do we need to revisit this issue now, or is the warning added in #380 enough?

We probably want to discuss this issue in the joint session with the PING working group.

> In the drive-by (mode 2) case where mDNS is used, we don't bind to a specific interface

The spec does not say anything about this, this might be an additional improvement that could be added. That said, I am not sold on exposing this information, similarly to concerns with http://wicg.github.io/netinfo/#dom-networkinformation-type.

I believe this field could be removed from the spec, that would not mandate existing implementations to stop exposing this field given that RTCIceCandidateStats is a dictionary.

**Comment by jan-ivar** [comment] 2019-10-30 15:46
[TPAC 2019 summary](https://lists.w3.org/Archives/Public/public-webrtc/2019Oct/0046.html): Broad interest in removing or gating networkType. Remove “vpn” value.

**Comment by snyderp** [comment] 2019-10-31 20:12
Just to second what was said at TPAC, and to second @youennf 's point.  Strong vote to remove the end point all together, for several reasons:

1) Its first hop, so its not going to be useful in almost all cases
2) It leaks hardware info, and since there is no permission that maps onto this hardware info, thats a hardline that shouldn't be crossed
3) More than just fingerprinting, you could likely use this info + IP to learn people's work, and maybe home too, etc (e.g. anywhere thats frequently visited + ethernet is work or home).  The privacy cost to this feature is very high.

**Comment by juberti** [comment] 2019-10-31 20:30
I'm pretty receptive to the privacy concerns as they are similar to the existing work on protecting local IP addresses. 

However I disagree that this information is not useful; the single bit of information to identify wifi versus mobile data, even as a noisy signal, has proven to be of significant use in debugging production services. (i.e., a surge of issues predominantly on mobile data can indicate a problem in a specific carrier's network).

My recommendation would be to treat this as privileged and only give it out when trust has been established, rather than removing altogether.

**Comment by aboba** [comment] 2019-10-31 20:36
Agree with Justin here.  We frequently see audio/video quality affected by issues on enterprise networks (wifi in particular) or carrier networks.  While the networkType only relates to the first-hop network, this is often where the problem is.  As an example, we have used this information to point customers to enterprise WiFi access points that were potentially installed inappropriately (e.g. on top of HVAC ducts so as to prevent signal propagation).

**Comment by snyderp** [comment] 2019-10-31 20:58
@juberti @aboba, i hear what you're saying, I understand the concerns.  Thank you for explaining :)

What is the imagined permission prompt then that'd ensure users what to help debug the problem?

E.g. I can imagine sometimes users want to help, but its inappropriate to assume that because i want to video conference (or whatever) I also want to tell the site about my network / other hardware / etc.  What do you all have planned?

**Comment by youennf** [comment] 2019-10-31 21:13
I think Justin is referring to using getUserMedia prompt (or getDisplayMedia) as a way to gate access to this stat.

FWIW, I don't think that this specific stat is as mature as the others.
The access model is not good enough right now, the exact definition of what should be exposed could potentially be redefined to decrease fingerprinting while maintaining some level of debuggability.
Also, other information that we currently leak like device labels or IP addresses are leaked to enable a feature for the user at the moment of the leak. The networkType stat is leaked to potentially and very indirectly improve the user experience in the future. This makes it a harder sell.

Given this, I would much prefer that this be moved to an extension spec so that it can mature at its own pace, while we can ship the first version of webrtc-pc and stats. I am happy to do the work, including the initial version of the corresponding extension spec.

**Comment by youennf** [comment] 2019-10-31 21:35
Below some further questions.

> the exact definition of what should be exposed could potentially be redefined

Would a single bit be sufficient (wireless/not wireless), or something like wired/wifi/wireless? 
We already expose private IP addresses in some cases. Would that information be sufficient for debugging in most cases? all cases? What are the cases where this is not sufficient?
Would some opaque ID that would identify the first hop/subnet be sufficient?

> The networkType stat is leaked to potentially and very indirectly improve the user experience in the future.

I understand that this was useful in the past and may be useful in the future.
So, how many times was it useful in the past? Do we have an idea of how much it is/will be useful? Can we compare the number of users benefiting from it compared to the number of users impacted by it?
If this is mostly useful for enterprise clients, should this stat be restricted to those cases only?

**Comment by youennf** [comment] 2019-11-28 14:17
Consensus during the interim meeting was to remove networkType from webrtc-stats as it is not yet mature enough.
This stat, or a new incarnation of it, will be moved for further improvement to an extension spec.

**Comment by youennf** [comment] 2019-11-28 15:54
Plan is to move this stat in https://github.com/w3c/webrtc-provisional-stats

**Comment by youennf** [comment] 2019-12-12 14:04
PR to move this stat in /webrtc-provisional-stats: https://github.com/w3c/webrtc-provisional-stats/pull/18

**Comment by alvestrand** [comment] 2020-04-21 11:59
No longer part of this spec, so closing.

**Closed by alvestrand** 2020-04-21 11:58 UTC
Labels: November 2019 Interim, TPAC 2018, TPAC 2019, privacy-tracker
