### ISSUE TITLE
RTCCodecStats in every getStats() is redundant.

### ISSUE THREAD

**Issue by karthikbr82** [w3c/webrtc-stats#306] opened 2018-01-23 14:38 UTC
RTCCodecStats does not change and significantly increases the size of stats output from getStats.
Hence receiving RTCCodecStats in every getStats call is unnecessary, can it be filtered out form the getStats stats output or can it be made to obtain RTCCodecStats from a different API call.

**Comment by fippo** [comment] 2018-01-23 14:49
they are is necessary to produce a fully linked graph that https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-codecid can link to.

Delta-compression schemes work quite nice fwiw.

**Comment by alvestrand** [comment] 2018-01-24 13:49
The decision was made rather early to make the stats a complete snapshot of the current PC state. Thus, we return many things that are stable between calls, and let the caller filter before storing.
Closing as "working as intended".

**Closed by alvestrand** 2018-01-24 13:49 UTC

**Comment by alvestrand** [comment] 2018-01-24 14:18
Note: Only codecs that are attached to a current track are returned. Section 6.1:
codec
Statistics for a codec that is currently being used by RTP streams being sent or received by this RTCPeerConnection object. It is accessed by the RTCCodecStats.

**Comment by karthikbr82** [comment] 2018-01-24 14:53
Thanks for the clarification. I raised this issue as the browser implmentations was returning all the codecs (around 52). If its the Statistics for a codec that is currently being used by RTP streams being sent or received by this RTCPeerConnection object then it should reduce the size already.
