### ISSUE TITLE
Consider making (aggregate) stats more accessible

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-stats#119] opened 2016-12-21 13:50 UTC
Feedback from web performance group review [1]:

"Stats are associated with each stream, which means that application developers have to manually instrument each stream. Is there a use case for analytics / third-party instrumentation to gather similar stats? E.g. it would be nice if existing RUM providers could auto-gather stats without monkey-patching all the WebRTC APIs to figure out when new streams are initiated, etc. 

Performance Timeline provides PerformanceObserver [2] interface which allows anyone to register and listen for events. It might be worth considering, if it makes sense, emitting some WebRTC related events via this mechanism... which could stream specific or aggregated. "

[1] https://lists.w3.org/Archives/Public/public-web-perf/2016Dec/0013.html

**Comment by alvestrand** [comment] 2017-01-10 11:18
Can someone expand RUM?

**Comment by alvestrand** [comment] 2017-01-10 11:22
Unclear what is being asked, and if the stats spec is the place for it.

It's possible that we're being asked for some method to expose all PeerConnecions on a page (would be a webrtc-pc change).
It's possible that we're being asked to emit events at WebRTC API calls (would also be a webrtc-pc change).

@igrigorik can you clarify?

**Comment by vr000m** [comment] 2017-01-10 21:59
Real User Monitor --> RUM.

**Comment by igrigorik** [comment] 2017-01-12 03:07
@alvestrand the observation above is simply that existing API's require deep+manual instrumentation of each stream to collect the stats. Now, imagine you're a third party RUM vendor (e.g. Soasta, New Relic, Google Analytics), or a sister-team on a large project that's monitoring performance of the application.. In order to obtain the stats, via current APIs, would require modifying the deployed code and/or doing some rather invasive injection. This is the problem, that [performance timeline](https://w3c.github.io/performance-timeline/) was designed to solve: a mechanism through which different subsystems can emit various perf-related metrics and events, and that subscribers can monitor to collect/aggregate/act on. 

So, my suggestion above is simply to consider if and where using this mechanism makes sense in the context of WebRTC stats.. Exposing metrics via perf timeline would enable the entire ecosystem of existing RUM vendors and telemetry scripts to get insights into WebRTC performance on their pages.

**Comment by alvestrand** [comment] 2017-03-14 08:50
I think this proposal is a new API development, and won't be done as part of this document.
Marking as "icebox" and closing it, since it needs to be done on another spec.

**Closed by alvestrand** 2017-03-14 08:50 UTC

**Comment by foolip** [comment] 2017-06-03 18:40
@henbos, this was linked from https://groups.google.com/a/chromium.org/d/msg/blink-dev/Kk4lCaCBaZU/WsF8TPCdBwAJ. Can you take a look to see if there's something that could be done here?

**Comment by henbos** [comment] 2017-06-05 08:28
I don't understand what is being proposed here.

As for having per-frame stats, measuring various parts of the pipeline, that might make sense to do here if aggregate values are of interest, but it does not make sense to do getStats or the like on a per-frame basis, that is infeasible for performance. Performance and frame-sensitive information should be exposed with a different API.

The referenced blink-dev discussion talks about end-to-end latency. We've talked about exposing that in getStats in #158 and #222. Further offline discussions have not brought us a solution to estimating this yet.
